CREATE SCHEMA xntrends;

DROP TABLE xntrends.USER;

CREATE TABLE xntrends.USER (
  ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  USER_NAME VARCHAR(500) NOT NULL,
  USER_ADDRESS VARCHAR(1500),
  USER_AGE INT(3)
)
  CHARSET = UTF8,
  ENGINE = InnoDB;

INSERT INTO xntrends.USER VALUES (null, 'Armen', 'Hakobyan 3', 15);
INSERT INTO xntrends.USER VALUES (null, 'David', 'Paronyan 11', 40);
INSERT INTO xntrends.USER VALUES (null, 'Harut', 'Tichina 1', 27);