DROP TABLE USER;

CREATE TABLE USER (
  ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  USER_NAME VARCHAR(500) NOT NULL,
  USER_ADDRESS VARCHAR(1500),
  USER_AGE INT(3)
)
  CHARSET = UTF8,
  ENGINE = InnoDB;

INSERT INTO USER VALUES (null, 'Armen', 'Hakobyan 3', 15);